import { useMemo } from 'react';
import {
  LineChart,
  Line,
  AreaChart,
  Area,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend
} from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import { AlertTriangle } from 'lucide-react';
import type { BuildingTelemetry, AnalyticsSummary, MarketStatus } from '@/types';

interface AnalyticsDashboardProps {
  buildings: BuildingTelemetry[];
  analytics: AnalyticsSummary | null;
  marketStatus: MarketStatus | null;
  history: { time: string; load: number; generation: number; efficiency: number; price?: number }[];
  onBuildingSelect?: (building: BuildingTelemetry) => void;
}

const COLORS = {
  green: '#22c55e',
  amber: '#f59e0b',
  red: '#ef4444',
  blue: '#3b82f6',
  purple: '#a855f7',
  cyan: '#06b6d4'
};

export function AnalyticsDashboard({ 
  buildings, 
  analytics, 
  marketStatus,
  history,
  onBuildingSelect
}: AnalyticsDashboardProps) {
  
  // Building status distribution for pie chart
  const statusDistribution = useMemo(() => {
    const data = [
      { name: 'Selling', value: buildings.filter(b => b.is_selling).length, color: COLORS.green },
      { name: 'Buying', value: buildings.filter(b => b.is_buying).length, color: COLORS.amber },
      { name: 'Critical', value: buildings.filter(b => b.is_critical).length, color: COLORS.red },
      { name: 'Balanced', value: buildings.filter(b => !b.is_selling && !b.is_buying && !b.is_critical).length, color: COLORS.blue }
    ];
    return data;
  }, [buildings]);

  // Battery SOC distribution
  const batteryDistribution = useMemo(() => {
    return buildings.map(b => ({
      id: b.building_id,
      soc: b.battery_soc,
      type: b.building_type
    })).sort((a, b) => b.soc - a.soc).slice(0, 15);
  }, [buildings]);

  const buyingPower = useMemo(() => buildings.filter(b => b.is_buying).reduce((sum, b) => sum + (b.load - b.solar_generation), 0), [buildings]);
  const sellingPower = useMemo(() => buildings.filter(b => b.is_selling).reduce((sum, b) => sum + (b.solar_generation - b.load), 0), [buildings]);

  return (
    <div className="space-y-4">
      {/* Key Metrics */}
      <div className="grid grid-cols-2 gap-2">
        <MetricCard
          title="Grid Efficiency"
          value={`${analytics?.grid_efficiency.toFixed(1) || 0}%`}
          trend="up"
          color={COLORS.green}
          description="Percentage of generated solar power intelligently consumed locally rather than exported."
        />
        <MetricCard
          title="Total Generation"
          value={`${analytics?.total_generation.toFixed(0) || 0}`}
          unit="kW"
          trend="up"
          color={COLORS.cyan}
          description="Instantaneous total power currently being generated by all solar panels."
        />
        <MetricCard
          title="Net Grid Flow"
          value={`${analytics?.net_grid_flow.toFixed(0) || 0}`}
          unit="kW"
          trend={analytics && analytics.net_grid_flow < 0 ? 'down' : 'up'}
          color={analytics && analytics.net_grid_flow < 0 ? COLORS.green : COLORS.amber}
          description="Net load drawn from traditional grid. Negative values indicate microgrid is exporting energy."
        />
        <MetricCard
          title="Avg Battery SoC"
          value={`${analytics?.avg_battery_soc.toFixed(1) || 0}%`}
          trend="stable"
          color={COLORS.purple}
          description="Average State of Charge for battery reserves across the entire grid."
        />
      </div>

      {/* Market Status */}
      {marketStatus && (
        <div className="grid grid-cols-2 gap-2">
          <HoverCard>
            <HoverCardTrigger asChild>
              <div className="bg-slate-900/80 border border-emerald-500/30 rounded-lg p-3 cursor-help hover:bg-slate-800/90 transition-colors overflow-hidden">
                <div className="text-xs text-slate-400">Market Price</div>
                <div className="text-sm font-bold text-emerald-400 truncate mt-1">
                  ${marketStatus.current_price.toFixed(3)}
                </div>
                <div className="text-[10px] text-slate-500">/kWh</div>
              </div>
            </HoverCardTrigger>
            <HoverCardContent side="bottom" className="w-64 bg-slate-900 border border-emerald-500/50 z-50 shadow-xl">
              <p className="text-sm text-slate-200">Current AI-negotiated dynamic price of energy per kilowatt-hour.</p>
            </HoverCardContent>
          </HoverCard>

          <HoverCard>
            <HoverCardTrigger asChild>
              <div className="bg-slate-900/80 border border-emerald-500/30 rounded-lg p-3 cursor-help hover:bg-slate-800/90 transition-colors overflow-hidden">
                <div className="text-xs text-slate-400">Active Sellers</div>
                <div className="text-lg font-bold text-green-400 mt-1">
                  {marketStatus.active_sellers}
                </div>
              </div>
            </HoverCardTrigger>
            <HoverCardContent side="bottom" className="w-64 bg-slate-900 border border-green-500/50 z-50 shadow-xl">
              <p className="text-sm text-slate-200 mb-2">Buildings with excess energy operating as P2P market sellers.</p>
              <div className="bg-green-500/10 p-2 rounded text-xs text-green-400 font-mono border border-green-500/30">
                Total Selling Power: {sellingPower.toFixed(1)} kW
              </div>
            </HoverCardContent>
          </HoverCard>

          <HoverCard>
            <HoverCardTrigger asChild>
              <div className="bg-slate-900/80 border border-emerald-500/30 rounded-lg p-3 cursor-help hover:bg-slate-800/90 transition-colors overflow-hidden">
                <div className="text-xs text-slate-400">Active Buyers</div>
                <div className="text-lg font-bold text-amber-400 mt-1">
                  {marketStatus.active_buyers}
                </div>
              </div>
            </HoverCardTrigger>
            <HoverCardContent side="bottom" className="w-64 bg-slate-900 border border-amber-500/50 z-50 shadow-xl">
              <p className="text-sm text-slate-200 mb-2">Buildings facing energy deficits operating as P2P market buyers.</p>
              <div className="bg-amber-500/10 p-2 rounded text-xs text-amber-400 font-mono border border-amber-500/30">
                Total Buying Power: {buyingPower.toFixed(1)} kW
              </div>
            </HoverCardContent>
          </HoverCard>

          <HoverCard>
            <HoverCardTrigger asChild>
              <div className="bg-slate-900/80 border border-emerald-500/30 rounded-lg p-3 cursor-help hover:bg-slate-800/90 transition-colors overflow-hidden">
                <div className="text-xs text-slate-400">Critical Buildings</div>
                <div className="text-lg font-bold text-red-400 mt-1">
                  {marketStatus.critical_buildings}
                </div>
              </div>
            </HoverCardTrigger>
            <HoverCardContent side="bottom" className="w-64 bg-slate-900 border border-red-500/50 z-50 shadow-xl">
              <p className="text-sm text-slate-200">Buildings with critically low battery (&lt;30%) needing urgent energy routing.</p>
            </HoverCardContent>
          </HoverCard>
        </div>
      )}

      {/* Critical Buildings Quick Action */}
      {buildings.filter(b => b.is_critical).length > 0 && (
        <Card className="bg-red-900/20 border-red-500/50 animate-in fade-in slide-in-from-top-4">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-red-400 flex items-center gap-2">
               <AlertTriangle className="w-4 h-4" /> Action Required: Critical Buildings
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
               {buildings.filter(b => b.is_critical).map(b => (
                 <Button 
                   key={b.building_id} 
                   variant="outline" 
                   size="sm" 
                   className="border-red-500/50 bg-red-500/10 hover:bg-red-500/30 text-red-300 transition-all font-mono"
                   onClick={() => onBuildingSelect && onBuildingSelect(b)}
                 >
                   ID: {b.building_id} ({b.battery_soc.toFixed(1)}%)
                 </Button>
               ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Charts Row 1 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Grid Performance Over Time */}
        <Card className="bg-slate-900/80 border-emerald-500/30">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-emerald-400">
              Grid Performance vs Traditional Grid
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={200}>
              <AreaChart data={history}>
                <defs>
                  <linearGradient id="colorEfficiency" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={COLORS.green} stopOpacity={0.3}/>
                    <stop offset="95%" stopColor={COLORS.green} stopOpacity={0}/>
                  </linearGradient>
                  <linearGradient id="colorTraditional" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={COLORS.red} stopOpacity={0.3}/>
                    <stop offset="95%" stopColor={COLORS.red} stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                <XAxis 
                  dataKey="time" 
                  stroke="#64748b"
                  tick={{ fontSize: 10 }}
                  tickFormatter={(value) => value.split(':')[1] || value}
                />
                <YAxis stroke="#64748b" tick={{ fontSize: 10 }} />
                <Tooltip
                  contentStyle={{ 
                    backgroundColor: '#0f172a', 
                    border: '1px solid #10b981',
                    borderRadius: '4px'
                  }}
                />
                <Area
                  type="monotone"
                  dataKey="efficiency"
                  stroke={COLORS.green}
                  fillOpacity={1}
                  fill="url(#colorEfficiency)"
                  name="EcoSync Grid"
                />
                <Area
                  type="monotone"
                  dataKey="traditional"
                  stroke={COLORS.red}
                  fillOpacity={1}
                  fill="url(#colorTraditional)"
                  name="Traditional Grid"
                />
                <Legend />
              </AreaChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Load vs Generation */}
        <Card className="bg-slate-900/80 border-emerald-500/30">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-emerald-400">
              Load vs Generation (Real-time)
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={200}>
              <LineChart data={history.slice(-20)}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                <XAxis 
                  dataKey="time" 
                  stroke="#64748b"
                  tick={{ fontSize: 10 }}
                  tickFormatter={(value) => value.split(':')[1] || value}
                />
                <YAxis stroke="#64748b" tick={{ fontSize: 10 }} />
                <Tooltip
                  contentStyle={{ 
                    backgroundColor: '#0f172a', 
                    border: '1px solid #10b981',
                    borderRadius: '4px'
                  }}
                />
                <Line
                  type="monotone"
                  dataKey="load"
                  stroke={COLORS.amber}
                  strokeWidth={2}
                  dot={false}
                  name="Load"
                />
                <Line
                  type="monotone"
                  dataKey="generation"
                  stroke={COLORS.green}
                  strokeWidth={2}
                  dot={false}
                  name="Generation"
                />
                <Legend />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      {/* Charts Row 2 */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Building Status Distribution */}
        <Card className="bg-slate-900/80 border-emerald-500/30">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-emerald-400">
              Building Status
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col items-center gap-3">
              <ResponsiveContainer width="100%" height={180}>
                <PieChart>
                  <Pie
                    data={statusDistribution}
                    cx="50%"
                    cy="50%"
                    innerRadius={30}
                    outerRadius={55}
                    paddingAngle={2}
                    dataKey="value"
                  >
                    {statusDistribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{ 
                      backgroundColor: '#0f172a', 
                      border: '1px solid #10b981',
                      borderRadius: '4px'
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
              {/* Custom legend that avoids the blue rectangle overlap */}
              <div className="flex flex-wrap justify-center gap-x-4 gap-y-1 text-xs">
                {statusDistribution.map((entry) => (
                  <div key={entry.name} className="flex items-center gap-2">
                    <span
                      className="w-2.5 h-2.5 rounded-full shrink-0"
                      style={{ backgroundColor: entry.color }}
                    />
                    <span className="text-slate-300">{entry.name}</span>
                    <span className="text-slate-500 ml-auto">{entry.value}</span>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Battery Levels */}
        <Card className="bg-slate-900/80 border-emerald-500/30 lg:col-span-2">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-emerald-400">
              Top Battery Levels by Building
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={180}>
              <BarChart data={batteryDistribution} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" horizontal={false} />
                <XAxis 
                  type="number" 
                  stroke="#64748b"
                  tick={{ fontSize: 10 }}
                  domain={[0, 100]}
                />
                <YAxis 
                  type="category" 
                  dataKey="id"
                  stroke="#64748b"
                  tick={{ fontSize: 10 }}
                  width={30}
                  tickFormatter={(value) => `#${value}`}
                />
                <Tooltip
                  contentStyle={{ 
                    backgroundColor: '#0f172a', 
                    border: '1px solid #10b981',
                    borderRadius: '4px'
                  }}
                  formatter={(value: number) => [`${value.toFixed(1)}%`, 'Battery SoC']}
                />
                <Bar 
                  dataKey="soc" 
                  radius={[0, 4, 4, 0]}
                  onClick={(data) => {
                    const b = buildings.find(bld => bld.building_id === data.id);
                    if (b && onBuildingSelect) onBuildingSelect(b);
                  }}
                  cursor="pointer"
                >
                  {batteryDistribution.map((entry, index) => (
                    <Cell 
                      key={`cell-${index}`} 
                      fill={entry.soc > 80 ? COLORS.green : entry.soc > 30 ? COLORS.amber : COLORS.red}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      {/* Charts Row 3 - Market Price */}
      <div className="grid grid-cols-1 gap-4">
        <Card className="bg-slate-900/80 border-emerald-500/30">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-emerald-400">
              Market Price History
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={200}>
              <AreaChart data={history}>
                <defs>
                  <linearGradient id="colorPrice" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={COLORS.amber} stopOpacity={0.4}/>
                    <stop offset="95%" stopColor={COLORS.amber} stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                <XAxis 
                  dataKey="time" 
                  stroke="#64748b" 
                  tick={{ fontSize: 10 }} 
                  tickFormatter={(val) => val.split(':')[1] || val} 
                />
                <YAxis 
                  stroke="#64748b" 
                  tick={{ fontSize: 10 }}
                  tickFormatter={(val) => `$${Number(val).toFixed(2)}`} 
                  domain={['dataMin - 0.05', 'dataMax + 0.05']}
                />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #10b981', borderRadius: '4px' }} 
                  formatter={(val: number) => [`$${val.toFixed(3)}`, 'Market Price']} 
                />
                <Area 
                  type="stepAfter" 
                  dataKey="price" 
                  stroke={COLORS.amber} 
                  fill="url(#colorPrice)" 
                  name="Market Price" 
                />
              </AreaChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// Metric Card Component
function MetricCard({ 
  title, 
  value, 
  unit,
  trend, 
  color,
  description
}: { 
  title: string; 
  value: string;
  unit?: string;
  trend: 'up' | 'down' | 'stable';
  color: string;
  description?: string;
}) {
  const trendIcon = trend === 'up' ? '↗' : trend === 'down' ? '↘' : '→';
  
  const content = (
    <div 
      className={`bg-slate-900/80 border rounded-lg p-3 transition-colors overflow-hidden ${description ? 'cursor-help hover:bg-slate-800/90' : ''}`}
      style={{ borderColor: `${color}40` }}
    >
      <div className="text-xs text-slate-400 truncate">{title}</div>
      <div className="flex items-baseline gap-1 mt-1 min-w-0">
        <span className="text-lg font-bold truncate" style={{ color }}>{value}</span>
        {unit && <span className="text-xs text-slate-400 shrink-0">{unit}</span>}
        <span className="text-[10px] shrink-0" style={{ color }}>{trendIcon}</span>
      </div>
    </div>
  );

  if (!description) return content;

  return (
    <HoverCard>
      <HoverCardTrigger asChild>
        {content}
      </HoverCardTrigger>
      <HoverCardContent side="bottom" className="w-64 bg-slate-900 border border-emerald-500/50 z-50 shadow-xl relative mt-1">
        <p className="text-sm text-slate-200">{description}</p>
      </HoverCardContent>
    </HoverCard>
  );
}
